from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field


class RiskLevel(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
    UNKNOWN = "UNKNOWN"


class EvidenceType(StrEnum):
    AUDIO = "AUDIO"
    VIDEO = "VIDEO"
    IMAGE = "IMAGE"
    FILE = "FILE"


class AnalyzeEvidenceRequest(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    evidence_record_id: str = Field(
        min_length=1,
        alias="evidenceRecordId",
        description="Backend identifier for the evidence record.",
    )
    alert_session_id: str = Field(
        min_length=1,
        alias="alertSessionId",
        description="Backend identifier for the alert session.",
    )
    evidence_type: EvidenceType = Field(
        alias="evidenceType",
        description="Backend evidence type, for example AUDIO, VIDEO or IMAGE.",
    )
    mime_type: str = Field(
        min_length=1,
        alias="mimeType",
        description="MIME type registered by the backend.",
    )
    size: int = Field(
        gt=0,
        description="Evidence file size in bytes.",
    )
    content_hash: str = Field(
        min_length=64,
        max_length=64,
        pattern=r"^[a-fA-F0-9]{64}$",
        alias="contentHash",
        description="SHA-256 content hash generated by the backend.",
    )


class AnalyzeEvidenceResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    risk_level: RiskLevel = Field(alias="riskLevel")
    confidence: float = Field(ge=0, le=1)
    summary: str
    detected_signals: list[str] = Field(alias="detectedSignals")
    should_escalate: bool = Field(alias="shouldEscalate")
