from enum import StrEnum
from datetime import datetime

from pydantic import BaseModel, ConfigDict, Field, model_validator


class RiskLevel(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
    UNKNOWN = "UNKNOWN"


class AnalysisStatus(StrEnum):
    QUEUED = "QUEUED"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    INCONCLUSIVE = "INCONCLUSIVE"


class RecommendedAction(StrEnum):
    NONE = "NONE"
    STORE_EVIDENCE = "STORE_EVIDENCE"
    REVIEW = "REVIEW"
    ESCALATE_CONTACTS = "ESCALATE_CONTACTS"


class EvidenceType(StrEnum):
    AUDIO = "AUDIO"
    VIDEO = "VIDEO"
    IMAGE = "IMAGE"
    FILE = "FILE"


class AudioLocationContext(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    latitude: float = Field(ge=-90, le=90)
    longitude: float = Field(ge=-180, le=180)
    accuracy_meters: float | None = Field(default=None, ge=0, alias="accuracyMeters")
    captured_at: datetime | None = Field(default=None, alias="capturedAt")


class AudioCaptureContext(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    capture_started_at: datetime | None = Field(default=None, alias="captureStartedAt")
    capture_ended_at: datetime | None = Field(default=None, alias="captureEndedAt")
    triggered_at: datetime | None = Field(default=None, alias="triggeredAt")
    pre_roll_ms: int | None = Field(default=None, ge=0, alias="preRollMs")
    post_roll_ms: int | None = Field(default=None, ge=0, alias="postRollMs")
    trigger_reasons: list[str] = Field(default_factory=list, alias="triggerReasons")
    local_confidence: float | None = Field(default=None, ge=0, le=1, alias="localConfidence")
    platform: str | None = Field(default=None, max_length=40)
    foreground: bool | None = None
    location: AudioLocationContext | None = None


class AnalyzeEvidenceRequest(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    evidence_record_id: str = Field(
        min_length=1,
        alias="evidenceRecordId",
        description="Backend identifier for the evidence record.",
    )
    alert_session_id: str = Field(
        min_length=1,
        alias="alertSessionId",
        description="Backend identifier for the alert session.",
    )
    evidence_type: EvidenceType = Field(
        alias="evidenceType",
        description="Backend evidence type, for example AUDIO, VIDEO or IMAGE.",
    )
    mime_type: str = Field(
        min_length=1,
        alias="mimeType",
        description="MIME type registered by the backend.",
    )
    size: int = Field(
        gt=0,
        description="Evidence file size in bytes.",
    )
    content_hash: str = Field(
        min_length=64,
        max_length=64,
        pattern=r"^[a-fA-F0-9]{64}$",
        alias="contentHash",
        description="SHA-256 content hash generated by the backend.",
    )
    storage_reference: str | None = Field(
        default=None,
        max_length=500,
        alias="storageReference",
        description="Opaque backend-owned reference for retrieving the evidence.",
    )
    capture_context: AudioCaptureContext | None = Field(
        default=None,
        alias="captureContext",
        description="Consent-aware capture metadata collected by the mobile app.",
    )

    @model_validator(mode="after")
    def validate_audio_contract(self) -> "AnalyzeEvidenceRequest":
        if self.evidence_type != EvidenceType.AUDIO:
            raise ValueError("Audio analysis v1 only supports AUDIO evidence.")

        if not self.mime_type.lower().startswith("audio/"):
            raise ValueError("Audio analysis v1 requires an audio MIME type.")

        return self


class EvidenceWindow(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    started_at: datetime | None = Field(default=None, alias="startedAt")
    ended_at: datetime | None = Field(default=None, alias="endedAt")
    duration_ms: int | None = Field(default=None, ge=0, alias="durationMs")


class TranscriptionSegment(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    start_ms: int = Field(ge=0, alias="startMs")
    end_ms: int = Field(ge=0, alias="endMs")
    text: str
    confidence: float | None = Field(default=None, ge=0, le=1)


class AudioTranscription(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    text: str
    language: str | None = Field(default=None, min_length=2, max_length=12)
    segments: list[TranscriptionSegment] = Field(default_factory=list)


class AcousticEvent(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    label: str
    start_ms: int = Field(ge=0, alias="startMs")
    end_ms: int = Field(ge=0, alias="endMs")
    confidence: float = Field(ge=0, le=1)
    source: str = Field(default="mock")


class ThreatMatch(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    label: str
    severity: RiskLevel
    confidence: float = Field(ge=0, le=1)
    start_ms: int | None = Field(default=None, ge=0, alias="startMs")
    end_ms: int | None = Field(default=None, ge=0, alias="endMs")
    evidence: str | None = Field(default=None, max_length=240)


class AnalysisProviderMetadata(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    provider: str
    model: str
    model_version: str = Field(alias="modelVersion")


class AnalyzeEvidenceResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    analysis_id: str = Field(alias="analysisId")
    analysis_version: str = Field(alias="analysisVersion")
    status: AnalysisStatus
    risk_level: RiskLevel = Field(alias="riskLevel")
    confidence: float = Field(ge=0, le=1)
    summary: str
    detected_signals: list[str] = Field(alias="detectedSignals")
    should_escalate: bool = Field(alias="shouldEscalate")
    recommended_action: RecommendedAction = Field(alias="recommendedAction")
    evidence_window: EvidenceWindow = Field(alias="evidenceWindow")
    transcription: AudioTranscription | None = None
    acoustic_events: list[AcousticEvent] = Field(
        default_factory=list,
        alias="acousticEvents",
    )
    threat_matches: list[ThreatMatch] = Field(
        default_factory=list,
        alias="threatMatches",
    )
    provider_metadata: AnalysisProviderMetadata = Field(alias="providerMetadata")
    processing_started_at: datetime = Field(alias="processingStartedAt")
    processing_finished_at: datetime = Field(alias="processingFinishedAt")
    latency_ms: int = Field(ge=0, alias="latencyMs")
    failure_reason: str | None = Field(default=None, alias="failureReason")
